### ISSUE TITLE
Critical: Unable to Restart Game After Dying or Completing the Game

### ISSUE THREAD

**Issue by zoranac** [Zerophase/DyMProject#1]
Build: Week 4

Bug: If the player wishes to start a new game after dying or complete the game, they are unable to because the death screen appears as soon as the new game starts. This can only be avoided by completely restarting the game.

Recreation: Start new game, fall into the pit (or die any other way), try and start a new game again, game over screen appears.

**Comment by Zerophase** [comment]
The static Id being used by the Entity Manager wasn't being reset when Entity Manager went out of scope.  Issue is fixed.
