### ISSUE TITLE
U/X: Jump Infinitely 

### ISSUE THREAD

**Issue by zoranac** [Zerophase/DyMProject#2]
Build: Week 4
Bug: Player can jump infinitely and get past all obstacles because of this.

**Comment by Zerophase** [comment]
I believe the issue has been fixed. I implemented a check for the player having the same y position for 5 frames. Technically, the player might be able to give themselves a very slight boost upwards, but if it does happen it isn't noticeable.

The only issue I could see with this is faster computers or slower computers will either get around this or never jump respectively. But, for now this is good enough.

For a more permanent solution we should implement ratio based on Time.deltaTime for calculating when jumping can happen again, or look into allowing our collision determine that. The latter is probably ideal, but takes manipulating the growth of the swept box.
