### ISSUE TITLE
U/X: Switching Planes Delay 

### ISSUE THREAD

**Issue by zoranac** [Zerophase/DyMProject#3]
Build: Week 4

Bug: Player must hold the bumpers for too long of a duration before the player actually locks into a different plane. Additionally, even though the player appears to have switched planes after pressing a bumper, it will move the player to the previous plane if the bumper is let go too quickly (less than 1 full second of the bumper being held down)

**Comment by Zerophase** [comment]
Yeah, I agree we should take the dodge delay out for now.  The plan was to have a dodge for enemies with fast attacks. But, nothing attacks that fast yet.

I do agree if we keep it in the delay should be half a second at most.
