### ISSUE TITLE
Menu Screen Controller Very (Too) Sensitive

### ISSUE THREAD

**Issue by zoranac** [Zerophase/DyMProject#5]
On the Main Menu, even the slightest nudge on the controller stick moves the selected button which frequently caused me to change which button I had selected unintentionally. Making the stick have to be pushed just a little more up or down for it to actually move should fix this.

**Comment by Zerophase** [comment]
The issue was from not having dead zones set on the controller. SO, it would usually register as technically being pressed. Dead zone applied. No more issue.
