### ISSUE TITLE
Incorrect Text On Instructions In Game

### ISSUE THREAD

**Issue by zoranac** [Zerophase/DyMProject#6]
At the beginning of the first level there is text saying "Move/Aim - Right Stick"

This is incorrect, Move/Aim is controlled with the Left Stick. 

Also the Controls screen is no longer accurate.

On a side note, I naturally have the tendency to want to aim with the right stick, and move with the left stick, it feels much more comfortable. Maybe test this control scheme out?

**Comment by Zerophase** [comment]
If we have the chance we'll definitely add multiple control schemes.  In our playtesting moving the aiming to the left stick, and freeing up the right hand for button pushes increased our intended arcade run and gun feel to the game.

**Comment by Zerophase** [comment]
The controls are now have the correct text in game.
