### ISSUE TITLE
Plane Shift and Stuck In Wall

### ISSUE THREAD

**Issue by zoranac** [Zerophase/DyMProject#8]
If there is a wall blocking your way on a plane (such as in the beginning of the first level) you can plane shift into it and get stuck in it (unless you plane shift out).

**Comment by Zerophase** [comment]
Yeah, the collision detection for plane shifting is in the process of being implemented.

**Comment by Zerophase** [comment]
I believe the player should no longer get stuck in walls. He can still plane shift in, but he shouldn't get stuck on the edges.

**Comment by Zerophase** [comment]
The player can no longer plane shift into walls.
